<a href="https://colab.research.google.com/github/Maxlab/Cordova-Examples/blob/master/LinRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
from torch.nn import Linear 

In [7]:
torch.manual_seed(1)
model = Linear(1,1)
print(model)
print(model.bias, model.weight)

Linear(in_features=1, out_features=1, bias=True)
Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [10]:
x = torch.tensor([[2.0],[3.3]])
model(x)

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)

In [0]:
class LR(torch.nn.Module):
  def __init__(self, in_f, out_f):
    super().__init__()
    self.linear = torch.nn.Linear(in_f, out_f)
    
  def forward(self, x):
    predict = self.linear(x)
    return predict

In [19]:
model = LR(1,1)
x = torch.Tensor([[1.0],[2.0]])

model.forward(x)

tensor([[0.0166],
        [0.1556]], grad_fn=<AddmmBackward>)